### PR TITLE
Thread permission check

### PR DESCRIPTION
**Pull request by Voroniyx**
adding a check if the bot has the permission in the thread

### CODE REVIEW

**Comment by Tolga1452** [comment]
this command's purpose is not managing the server. let the user delete their own threads

**Comment by Voroniyx** [comment]
yes but i just displays the thinking message, isnt this annoying?

**Comment by Tolga1452** [comment]
> yes but i just displays the thinking message, isnt this annoying?

because it deletes the channel that you used the command in

**Comment by Voroniyx** [comment]
but, if it cant delete the thread then nothing happens

**Comment by Tolga1452** [comment]
> but, if it cant delete the thread then nothing happens

oh wait, so you mean the checking permissions for bot?

**Comment by Voroniyx** [comment]
yes, it just checks for the permissions for the bot, not the member. if the bot has the permissions to delete the thread.
image

**Comment by Voroniyx** [comment]
Ok, yeah. Your way is better

**Comment by Voroniyx** [comment]
PR was replaced by Commit 7f7fab62c0f9dcb82f1b9c5c35898c9df123e7f7.

**Pull request closed without merging**
